excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://eljayyy.github.io
name: On the West Coast
description: Personal blog of Alex LaJeunesse.
author: Alex LaJeunesse
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 